### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by GegznaV** [bryanhanson/roxut#10]
Add at least a few unit tests for this package. Code from `@examples` can be used as the basis for unit tests.

**Comment by bryanhanson** [comment]
Finally figured out a way to get meaningful UTs working.  Now checks the contents of the generated UT files and checks that `testthat` and `tinytest` produce the same test lines.  Fixed in https://github.com/bryanhanson/roxut/commit/8928fdf51842a4d8c01d1e3f15b08461855bd50d will be preparing for CRAN later today probably.
